### ISSUE TITLE
Search for secrets by secret name

### ISSUE THREAD

**Issue by larserikfinholt** [thycotic/sdk-documentation#12]
Hi!

The docs says that this is the way we should get a secret.
`var password = client.GetSecretField(<SECRET ID>,"password");`

So if our our app requires lots of secrets, we whould have to hardcode all this integers into our config? Or is it possible to search for a secret by its name, and then grab the id from the search result?

Or even better: The secretName should be uniqe, so that a user could get the secret directly by secretName.

Or maybe I'm missing something? Are there other ways we could retrive multiple secrets?

**Comment by JasonRowe** [comment]
I have my own search for now using 

/api/v1/secrets?secretTemplateName{templateName}&filter.searchText={searchText}

Would be nice if the client supported a more flexible approach or are we doing it wrong?

**Comment by wsmelton** [comment]
The Client SDK at this time does not support a search function/method. You can contact your Thycotic account rep to submit a feature request.
