### ISSUE TITLE
ProcessCreateResponse throws Null Reference Exception 

### ISSUE THREAD

**Issue by randybarca** [thycotic/sdk-documentation#7]
I am unable to get details of a failure to create the connection to thycotic when calling the Configure method on the SecretServerClient. In my instance the API Rule being sent in didn't match what was expected. Instead of helpful details about why this failed it throws a System.NullReferenceException: 'Object reference not set to an instance of an object.' without any details. After decompiling the assembly and recreating the class I was able to step into the method and find details about the actual issue. After checking to see if the !response.IsSuccessStatusCode it continues to use the response.Model object and throws the null reference exception. 

![image](https://user-images.githubusercontent.com/12731696/46672115-3d627700-cb9c-11e8-8c33-1dbe71f38e4a.png)

**Comment by wsmelton** [comment]
A new release of the Client SDK, 1.5.0, has been released as of February 2021. 

If you continue to have issues please submit a case request to Thycotic Support.
