### ISSUE TITLE
Newtonsoft.Json reference exception.

### ISSUE THREAD

**Issue by pvbinu28** [thycotic/sdk-documentation#8]
After adding the Interceptor module, getting the following error error.

**Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)** 

Application is referring to Newtonsoft.Json DLLs Version 9.0.1

**Comment by amshekar** [comment]
Faced same issues .
By updating the Newtonsoft json package through nuget  solved the issues
`<package id="Newtonsoft.Json" version="11.0.2" targetFramework="net462" />`

**Comment by amshekar** [comment]
@pvbinu28  If you still face the issue after updating . Delete the bin folder rebuild the application and run.

**Comment by wsmelton** [comment]
A new release of the SDK has been published as of February 2021. 

If you have issues using the Client SDK please submit those via your Thycotic Support.
